### ISSUE TITLE
How to clone a repo? 

### ISSUE THREAD

**Issue by manzomium** [mattjaybe/sd-wildcards#1]
Sorry to post this as an issue but there's no discussion tab here 

I'm quite ignorant re repos python etc so I'd like to know for to clone this repo into the DP wildcard folder. Thanks!

**Comment by mattjaybe** [comment]
No worries! To clone a repo, you'll first need to have Git installed. If you're on Windows, you can get it here: https://gitforwindows.org/

Then, once Dynamic Prompts is installed, navigate to this folder using Windows Explorer: \stable-diffusion-webui\extensions\sd-dynamic-prompts

In Windows Explorer's address bar at the top, type in `cmd`, and a command prompt will open.  Then put this in there:

`git clone https://github.com/mattjaybe/sd-wildcards.git`

It'll quickly download the wildcards folder into the proper place. You don't have to reboot Stable Diffusion or anything, it'll work as soon as you invoke a wildcard in your prompt.

**Comment by manzomium** [comment]
thanks, it worked! however, I expected it to install the sd-wildcards folder inside DP wildcard folder, it installed in the upper level instead. no worries, I copy/pasted your wildcards into the right place, in a separate folder. 

The idea of using ChatGPT is simply genius!
